syntax = "proto3";

message SubirFotoRequest {
  string idReview = 1;
  int32 indice = 2;         
  string extension = 3;      
  bytes datos = 4;            
}

message SubirFotoResponse {
  bool success = 1;
  string message = 2;
}

message ChunkVideoRequest {
  string idReview = 1;
  string extension = 2;       
  bytes chunk = 3;           
  int32 chunkIndex = 4;      
  int32 totalChunks = 5;     
}

message SubirVideoResponse {
  bool success = 1;
  string message = 2;
}

message ObtenerFotosRequest {
  string idReview = 1;
}

message FotoReviewInfo {
  int32 indice = 1;
  bytes datos = 2;
}

message ObtenerFotosResponse {
  repeated FotoReviewInfo fotos = 1;
  string idReview = 2;
}

message ObtenerVideoRequest {
  string idReview = 1;
}

message VideoChunk {
  bytes chunk = 1;
  int32 chunkIndex = 2;
  int32 totalChunks = 3;
}

message ObtenerMetadataRequest {
  string idReview = 1;
}

message MetadataResponse {
  int32 numFotos = 1;
  int32 numVideos = 2;
}

message EliminarArchivosRequest {
  string idReview = 1;
}

message EliminarArchivosResponse {
  bool success = 1;
  string message = 2;
}

service ReviewMultimedia {
  rpc SubirFoto(SubirFotoRequest) returns (SubirFotoResponse);
  rpc ObtenerFotos(ObtenerFotosRequest) returns (ObtenerFotosResponse);
  
  rpc SubirVideo(stream ChunkVideoRequest) returns (SubirVideoResponse);
  rpc ObtenerVideo(ObtenerVideoRequest) returns (stream VideoChunk);
  
  rpc ObtenerMetadata(ObtenerMetadataRequest) returns (MetadataResponse);
  rpc EliminarArchivos(EliminarArchivosRequest) returns (EliminarArchivosResponse);
}