# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import Fotos_De_Perfil_pb2 as Fotos__De__Perfil__pb2
GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in Fotos_De_Perfil_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FotosDePerfilStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubirFoto = channel.unary_unary(
                '/FotosDePerfil/SubirFoto',
                request_serializer=Fotos__De__Perfil__pb2.FotoRequest.SerializeToString,
                response_deserializer=Fotos__De__Perfil__pb2.FotoResponse.FromString,
                _registered_method=True)
        self.ObtenerFoto = channel.unary_unary(
                '/FotosDePerfil/ObtenerFoto',
                request_serializer=Fotos__De__Perfil__pb2.FotoRequest.SerializeToString,
                response_deserializer=Fotos__De__Perfil__pb2.FotoResponse.FromString,
                _registered_method=True)
        self.ActualizarFoto = channel.unary_unary(
                '/FotosDePerfil/ActualizarFoto',
                request_serializer=Fotos__De__Perfil__pb2.FotoRequest.SerializeToString,
                response_deserializer=Fotos__De__Perfil__pb2.FotoResponse.FromString,
                _registered_method=True)


class FotosDePerfilServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubirFoto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerFoto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarFoto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FotosDePerfilServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubirFoto': grpc.unary_unary_rpc_method_handler(
                    servicer.SubirFoto,
                    request_deserializer=Fotos__De__Perfil__pb2.FotoRequest.FromString,
                    response_serializer=Fotos__De__Perfil__pb2.FotoResponse.SerializeToString,
            ),
            'ObtenerFoto': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerFoto,
                    request_deserializer=Fotos__De__Perfil__pb2.FotoRequest.FromString,
                    response_serializer=Fotos__De__Perfil__pb2.FotoResponse.SerializeToString,
            ),
            'ActualizarFoto': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarFoto,
                    request_deserializer=Fotos__De__Perfil__pb2.FotoRequest.FromString,
                    response_serializer=Fotos__De__Perfil__pb2.FotoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FotosDePerfil', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FotosDePerfil', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FotosDePerfil(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubirFoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FotosDePerfil/SubirFoto',
            Fotos__De__Perfil__pb2.FotoRequest.SerializeToString,
            Fotos__De__Perfil__pb2.FotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerFoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FotosDePerfil/ObtenerFoto',
            Fotos__De__Perfil__pb2.FotoRequest.SerializeToString,
            Fotos__De__Perfil__pb2.FotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarFoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FotosDePerfil/ActualizarFoto',
            Fotos__De__Perfil__pb2.FotoRequest.SerializeToString,
            Fotos__De__Perfil__pb2.FotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
