# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import Multimedia_De_Resenia_pb2 as Multimedia__De__Resenia__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in Multimedia_De_Resenia_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReviewMultimediaStub(object):
    """========== SERVICIO ==========
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubirFoto = channel.unary_unary(
                '/ReviewMultimedia/SubirFoto',
                request_serializer=Multimedia__De__Resenia__pb2.SubirFotoRequest.SerializeToString,
                response_deserializer=Multimedia__De__Resenia__pb2.SubirFotoResponse.FromString,
                _registered_method=True)
        self.ObtenerFotos = channel.unary_unary(
                '/ReviewMultimedia/ObtenerFotos',
                request_serializer=Multimedia__De__Resenia__pb2.ObtenerFotosRequest.SerializeToString,
                response_deserializer=Multimedia__De__Resenia__pb2.ObtenerFotosResponse.FromString,
                _registered_method=True)
        self.SubirVideo = channel.stream_unary(
                '/ReviewMultimedia/SubirVideo',
                request_serializer=Multimedia__De__Resenia__pb2.ChunkVideoRequest.SerializeToString,
                response_deserializer=Multimedia__De__Resenia__pb2.SubirVideoResponse.FromString,
                _registered_method=True)
        self.ObtenerVideo = channel.unary_stream(
                '/ReviewMultimedia/ObtenerVideo',
                request_serializer=Multimedia__De__Resenia__pb2.ObtenerVideoRequest.SerializeToString,
                response_deserializer=Multimedia__De__Resenia__pb2.VideoChunk.FromString,
                _registered_method=True)
        self.ObtenerMetadata = channel.unary_unary(
                '/ReviewMultimedia/ObtenerMetadata',
                request_serializer=Multimedia__De__Resenia__pb2.ObtenerMetadataRequest.SerializeToString,
                response_deserializer=Multimedia__De__Resenia__pb2.MetadataResponse.FromString,
                _registered_method=True)
        self.EliminarArchivos = channel.unary_unary(
                '/ReviewMultimedia/EliminarArchivos',
                request_serializer=Multimedia__De__Resenia__pb2.EliminarArchivosRequest.SerializeToString,
                response_deserializer=Multimedia__De__Resenia__pb2.EliminarArchivosResponse.FromString,
                _registered_method=True)


class ReviewMultimediaServicer(object):
    """========== SERVICIO ==========
    """

    def SubirFoto(self, request, context):
        """Fotos: unary (normal)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerFotos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubirVideo(self, request_iterator, context):
        """Videos: streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerMetadata(self, request, context):
        """Otros
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarArchivos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReviewMultimediaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubirFoto': grpc.unary_unary_rpc_method_handler(
                    servicer.SubirFoto,
                    request_deserializer=Multimedia__De__Resenia__pb2.SubirFotoRequest.FromString,
                    response_serializer=Multimedia__De__Resenia__pb2.SubirFotoResponse.SerializeToString,
            ),
            'ObtenerFotos': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerFotos,
                    request_deserializer=Multimedia__De__Resenia__pb2.ObtenerFotosRequest.FromString,
                    response_serializer=Multimedia__De__Resenia__pb2.ObtenerFotosResponse.SerializeToString,
            ),
            'SubirVideo': grpc.stream_unary_rpc_method_handler(
                    servicer.SubirVideo,
                    request_deserializer=Multimedia__De__Resenia__pb2.ChunkVideoRequest.FromString,
                    response_serializer=Multimedia__De__Resenia__pb2.SubirVideoResponse.SerializeToString,
            ),
            'ObtenerVideo': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtenerVideo,
                    request_deserializer=Multimedia__De__Resenia__pb2.ObtenerVideoRequest.FromString,
                    response_serializer=Multimedia__De__Resenia__pb2.VideoChunk.SerializeToString,
            ),
            'ObtenerMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerMetadata,
                    request_deserializer=Multimedia__De__Resenia__pb2.ObtenerMetadataRequest.FromString,
                    response_serializer=Multimedia__De__Resenia__pb2.MetadataResponse.SerializeToString,
            ),
            'EliminarArchivos': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarArchivos,
                    request_deserializer=Multimedia__De__Resenia__pb2.EliminarArchivosRequest.FromString,
                    response_serializer=Multimedia__De__Resenia__pb2.EliminarArchivosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ReviewMultimedia', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ReviewMultimedia', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReviewMultimedia(object):
    """========== SERVICIO ==========
    """

    @staticmethod
    def SubirFoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReviewMultimedia/SubirFoto',
            Multimedia__De__Resenia__pb2.SubirFotoRequest.SerializeToString,
            Multimedia__De__Resenia__pb2.SubirFotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerFotos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReviewMultimedia/ObtenerFotos',
            Multimedia__De__Resenia__pb2.ObtenerFotosRequest.SerializeToString,
            Multimedia__De__Resenia__pb2.ObtenerFotosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubirVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ReviewMultimedia/SubirVideo',
            Multimedia__De__Resenia__pb2.ChunkVideoRequest.SerializeToString,
            Multimedia__De__Resenia__pb2.SubirVideoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ReviewMultimedia/ObtenerVideo',
            Multimedia__De__Resenia__pb2.ObtenerVideoRequest.SerializeToString,
            Multimedia__De__Resenia__pb2.VideoChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReviewMultimedia/ObtenerMetadata',
            Multimedia__De__Resenia__pb2.ObtenerMetadataRequest.SerializeToString,
            Multimedia__De__Resenia__pb2.MetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarArchivos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ReviewMultimedia/EliminarArchivos',
            Multimedia__De__Resenia__pb2.EliminarArchivosRequest.SerializeToString,
            Multimedia__De__Resenia__pb2.EliminarArchivosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
